version: '3'
services:
  
  backend:
    image: flask
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: 10.0.33.32
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: myDb
   
